##
##   Copyright (c) 2020 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
# Role for updating git on RHEL7-based distros to resolve 'go get' issues on some projects

# install deps
- name: install deps
  package:
    name:
      - gettext-devel
      - openssl-devel
      - perl-CPAN
      - perl-devel
      - zlib-devel
      - curl-devel
    state: present

- name: download git tarball
  unarchive:
    src: "{{ git_tarball_url }}"
    dest: /usr/src/
    remote_src: yes
    mode: 0755

- name: make configure
  make:
    target: configure
    chdir: "/usr/src/git-{{ git_version }}"

- name: configure
  command: ./configure --prefix=/usr/local
  args:
    chdir: "/usr/src/git-{{ git_version }}"
  changed_when: true

- name: build
  make:
    chdir: "/usr/src/git-{{ git_version }}"

- name: install
  make:
    target: install
    chdir: "/usr/src/git-{{ git_version }}"
