# How to use this file:
# --------------------
# <feature> can be:
# - on (included and enabled)
# - optional (included in vars but disabled)
# - off (not included, might as well drop it from the profile section)
#
# features:
# - vm_mode             - is 'optional(false)' on k8s and is 'on(true)' on vm_host and on VMs
# - on_vms              - is 'optional(false)' on k8s and on vm_host and is 'on(true)' on VMs
# - cloud_mode
# - nfd
# - kube_dashboard
# - isolcpu
# - cpusets
# - intel_cpu_controlplane
# - native_cpu_manager
# - bond_cni
# - topology_manager
# - sriov_operator
# - sriov_network_dp
# - nic_drivers
# - sgx
# - sgx_dp
# - kmra:
#     sbx
#     oran
#     pccs
#     apphsm
#     ctk_demo
# - tcs
# - tac
# - qat
# - dsa
# - gpu
# - gpu_dp
# - openssl
# - tas
# - gas
# - ddp
# - network_userspace
# - dpdk
# - ovs_dpdk
# - sst
# - power:
#     manager
#     pstate
#     cstate
#     uncore_frequency
# - telemetry:
#     prometheus
#     collectd
#     telegraf
#     jaeger
#     opentelemetry
#     elasticsearch
#     kibana
# - wireguard
# - multus
# - minio
# - cert_manager
# - registry
# - hugepages
# - istio_service_mesh
#     enabled
#     tcpip_bypass_ebpf
#     tls_splicing
#     sgx_signer
#     intel_preview
# - linkerd_service_mesh
#     enabled
# - intel_ethernet_operator
#     enabled
#     flow_config
#     ddp
#     fw_update
# - intel_sriov_fec_operator
# - intel_oneapi
#     base
#     ai
# - intel_flexran
# - tadk
# - cadvisor
---
access:
  name: access
  cloud_mode: on
  vm_mode: off
  on_vms: off
  nfd: on
  kube_dashboard: off
  isolcpu: optional
  cpusets: optional
  native_cpu_manager: off
  topology_manager: off
  sriov_operator: off
  sriov_network_dp: off
  nic_drivers: off
  bond_cni: off
  qat: off
  qat_dp: off
  openssl: off
  dsa: off
  dsa_dp: off
  dlb: off
  dlb_dp: off
  gpu: off
  gpu_dp: off
  sgx: off
  sgx_dp: off
  kmra:
    sbx: off
    oran: off
    pccs: off
    apphsm: off
    ctk_demo: off
  tcs: off
  tac: off
  tas: off
  gas: off
  ddp: off
  network_userspace: off
  dpdk: on
  ovs_dpdk: off
  sst: off
  power:
    manager: off
    pstate: off
    cstate: off
    uncore_frequency: off
  telemetry:
    prometheus: on
    collectd: off
    telegraf: on
    jaeger: on
    opentelemetry: on
    elasticsearch: on
    kibana: on
  istio_service_mesh:
    enabled: off
    tcpip_bypass_ebpf: off
    tls_splicing: off
    sgx_signer: off
    intel_preview: off
  linkerd_service_mesh:
    enabled: off
  wireguard: off
  multus: on
  firewall: off
  minio: off
  cert_manager: on
  registry: off
  hugepages: on
  intel_ethernet_operator:
    enabled: off
    flow_config: off
    ddp: off
    fw_update: off
  intel_sriov_fec_operator: off
  intel_oneapi:
    base: off
    ai: off
  intel_flexran: off
  adq_dp: off
  cadvisor: on

basic:
  name: basic
  cloud_mode: on
  vm_mode: off
  on_vms: off
  nfd: on
  kube_dashboard: off
  isolcpu: optional
  cpusets: optional
  topology_manager: off
  sriov_operator: off
  sriov_network_dp: off
  nic_drivers: off
  dpdk: optional
  power:
    manager: off
    pstate: optional
    cstate: optional
    uncore_frequency: off
  telemetry:
    prometheus: on
    collectd: off
    telegraf: on
    jaeger: on
    opentelemetry: on
    elasticsearch: on
    kibana: on
  wireguard: off
  multus: on
  firewall: off
  cert_manager: on
  registry: off
  hugepages: optional
  intel_ethernet_operator:
    enabled: off
    flow_config: off
    fw_update: off
  adq_dp: off
  intel_oneapi:
    base: optional
    ai: optional
  cadvisor: on

full_nfv:
  name: full_nfv
  cloud_mode: on
  vm_mode: off
  on_vms: off
  nfd: on
  kube_dashboard: off
  isolcpu: optional
  cpusets: optional
  intel_cpu_controlplane: optional
  native_cpu_manager: off
  topology_manager: off
  sriov_operator: off
  sriov_network_dp: off
  nic_drivers: off
  bond_cni: off
  qat: off
  qat_dp: off
  openssl: off
  dsa: off
  dsa_dp: off
  dlb: off
  dlb_dp: off
  gpu: off
  gpu_dp: off
  sgx: off
  sgx_dp: off
  kmra:
    sbx: off
    oran: off
    pccs: off
    apphsm: off
    ctk_demo: off
  tcs: off
  tac: off
  tas: off
  gas: off
  ddp: off
  network_userspace: on
  dpdk: on
  ovs_dpdk: on
  sst: off
  power:
    manager: off
    pstate: optional
    cstate: optional
    uncore_frequency: off
  telemetry:
    prometheus: on
    collectd: off
    telegraf: on
    jaeger: on
    opentelemetry: on
    elasticsearch: on
    kibana: on
  istio_service_mesh:
    enabled: on
    tcpip_bypass_ebpf: off
    tls_splicing: on
    sgx_signer: off
    intel_preview: optional
  linkerd_service_mesh:
    enabled: optional
  wireguard: off
  multus: on
  firewall: off
  minio: off
  cert_manager: on
  registry: off
  hugepages: on
  intel_ethernet_operator:
    enabled: off
    flow_config: off
    ddp: off
    fw_update: off
  intel_sriov_fec_operator: off
  intel_oneapi:
    base: optional
    ai: optional
  intel_flexran: off
  tadk: on
  adq_dp: off
  cadvisor: on

on_prem:
  name: on_prem
  cloud_mode: on
  vm_mode: off
  on_vms: off
  nfd: on
  kube_dashboard: off
  isolcpu: optional
  cpusets: optional
  native_cpu_manager: off
  topology_manager: off
  sriov_operator: off
  sriov_network_dp: off
  nic_drivers: off
  sgx: off
  sgx_dp: off
  kmra:
    sbx: off
    oran: off
    pccs: off
    apphsm: off
    ctk_demo: off
  tcs: off
  tac: off
  qat: off
  qat_dp: off
  dsa: off
  dsa_dp: off
  dlb: off
  dlb_dp: off
  openssl: off
  tas: off
  dpdk: on
  bond_cni: off
  sst: off
  power:
    manager: off
    pstate: off
    cstate: optional
    uncore_frequency: off
  telemetry:
    prometheus: on
    collectd: off
    telegraf: on
    jaeger: on
    opentelemetry: on
    elasticsearch: on
    kibana: on
  istio_service_mesh:
    enabled: on
    tcpip_bypass_ebpf: off
    tls_splicing: on
    sgx_signer: off
    intel_preview: optional
  linkerd_service_mesh:
    enabled: optional
  wireguard: off
  multus: on
  firewall: off
  cert_manager: on
  registry: off
  hugepages: on
  intel_ethernet_operator:
    enabled: off
    flow_config: off
    fw_update: off
  adq_dp: off
  intel_oneapi:
    base: optional
    ai: optional
  cadvisor: on

regional_dc:
  name: regional_dc
  cloud_mode: on
  vm_mode: off
  on_vms: off
  nfd: on
  kube_dashboard: off
  isolcpu: optional
  cpusets: optional
  topology_manager: off
  sriov_operator: off
  sriov_network_dp: off
  nic_drivers: off
  native_cpu_manager: off
  gpu: off
  gpu_dp: off
  sgx: off
  sgx_dp: off
  kmra:
    sbx: off
    oran: off
    pccs: off
    apphsm: off
    ctk_demo: off
  tcs: off
  tac: off
  tas: off
  gas: off
  dpdk: optional
  power:
    manager: off
    pstate: optional
    cstate: optional
    uncore_frequency: off
  telemetry:
    prometheus: on
    collectd: off
    telegraf: on
    jaeger: on
    opentelemetry: on
    elasticsearch: on
    kibana: on
  istio_service_mesh:
    enabled: on
    tcpip_bypass_ebpf: off
    tls_splicing: on
    sgx_signer: off
    intel_preview: optional
  linkerd_service_mesh:
    enabled: optional
  wireguard: off
  multus: on
  firewall: off
  cert_manager: on
  registry: off
  hugepages: optional
  intel_ethernet_operator:
    enabled: off
    flow_config: off
    fw_update: off
  adq_dp: off
  intel_oneapi:
    base: optional
    ai: optional
  cadvisor: on

remote_fp:
  name: remote_fp
  cloud_mode: on
  vm_mode: off
  on_vms: off
  nfd: on
  kube_dashboard: off
  isolcpu: optional
  cpusets: optional
  intel_cpu_controlplane: optional
  native_cpu_manager: off
  topology_manager: off
  sriov_operator: off
  sriov_network_dp: off
  nic_drivers: off
  sgx: off
  sgx_dp: off
  kmra:
    sbx: off
    oran: off
    pccs: off
    apphsm: off
    ctk_demo: off
  tcs: off
  tac: off
  qat: off
  qat_dp: off
  dsa: off
  dsa_dp: off
  dlb: off
  dlb_dp: off
  openssl: off
  tas: off
  ddp: off
  bond_cni: off
  network_userspace: optional
  dpdk: on
  sst: off
  power:
    manager: off
    pstate: off
    cstate: optional
    uncore_frequency: off
  telemetry:
    prometheus: on
    collectd: off
    telegraf: optional
    jaeger: optional
    opentelemetry: optional
    elasticsearch: optional
    kibana: optional
  istio_service_mesh:
    enabled: optional
    tcpip_bypass_ebpf: off
    tls_splicing: optional
    sgx_signer: off
    intel_preview: optional
  linkerd_service_mesh:
    enabled: optional
  wireguard: off
  multus: on
  firewall: off
  cert_manager: on
  registry: off
  hugepages: on
  intel_ethernet_operator:
    enabled: off
    flow_config: off
    ddp: off
    fw_update: off
  adq_dp: off
  intel_oneapi:
    base: optional
    ai: optional
  cadvisor: optional

build_your_own:
  name: build_your_own
  cloud_mode: on
  vm_mode: off
  on_vms: off
  nfd: optional
  kube_dashboard: off
  isolcpu: optional
  cpusets: optional
  intel_cpu_controlplane: optional
  native_cpu_manager: off
  topology_manager: off
  sriov_operator: off
  sriov_network_dp: off
  nic_drivers: off
  bond_cni: off
  qat: off
  qat_dp: off
  openssl: off
  dsa: off
  dsa_dp: off
  gpu: off
  gpu_dp: off
  sgx: off
  sgx_dp: off
  kmra:
    sbx: off
    oran: off
    pccs: off
    apphsm: off
    ctk_demo: off
  tcs: off
  tac: off
  tas: off
  gas: off
  ddp: off
  network_userspace: optional
  dpdk: optional
  ovs_dpdk: optional
  sst: off
  power:
    manager: off
    pstate: off
    cstate: optional
    uncore_frequency: off
  telemetry:
    prometheus: optional
    collectd: off
    telegraf: optional
    jaeger: optional
    opentelemetry: optional
    elasticsearch: optional
    kibana: optional
  istio_service_mesh:
    enabled: optional
    tcpip_bypass_ebpf: off
    tls_splicing: optional
    sgx_signer: off
    intel_preview: optional
  linkerd_service_mesh:
    enabled: optional
  wireguard: off
  multus: optional
  firewall: off
  minio: off
  cert_manager: optional
  registry: off
  hugepages: optional
  intel_ethernet_operator:
    enabled: off
    flow_config: off
    ddp: off
    fw_update: off
  intel_sriov_fec_operator: off
  intel_oneapi:
    base: optional
    ai: optional
  intel_flexran: off
  tadk: optional
  adq_dp: off
  cadvisor: optional
