---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-entrypoint
  namespace: {{ .Release.Namespace }}
data:
  apphsm_commands.sh: |
    #!/bin/bash -e
    set -eu
    export no_proxy="$no_proxy,localhost,127.0.0.1/8"

    mkdir -p /tmp/apphsm
    cp /opt/intel/ca/{apphsm.crt,apphsm.key,ca.crt} /tmp/apphsm/
    cp /opt/intel/apphsm/apphsm.conf /tmp/apphsm/apphsm.conf
    cd /tmp/apphsm/

    {{- range $key := .Values.apphsm.keys }}
    echo "Create private key & certificate..."
    openssl req \
    -nodes \
    -x509 \
    -newkey rsa:3072 \
    -keyout {{ $key.token_key }} \
    -out {{ $key.token_cert }} \
    -subj "/O={{ $key.crt_subj.O }}/CN={{ $key.crt_subj.CN }}"

    echo "Create sample token..."
    sample_key_gen \
    --so-pin {{ $.Values.apphsm.default_so_pin }} \
    --pin {{ $key.pin }} \
    --token-label {{ $key.token_name }} \
    --key-label {{ $key.key_name }} \
    --import-key {{ $key.token_key }}

    echo "Remove private key as the key is stored in the HSM..."
    rm -rf {{ $key.token_key }}
    {{ end }}

    echo -e "\033[0;31m------------------------------------------------------------"
    echo -e "KMRA (Key Management Reference Application) is a proof-of-concept"
    echo -e "software not suitable for production usage. AppHSM Key Server has"
    echo -e "limited functionality and provisions private keys to non-production"
    echo -e "SGX enclaves. Please note that the enclave is signed with a test"
    echo -e "signing key. A production enclave should go through the process of"
    echo -e "signing an enclave as explained in the section Enclave Signing Tool"
    echo -e "in the Intel(R) SGX Developer Reference for Linux* OS"
    echo -e "(https://download.01.org/intel-sgx/latest/linux-latest/docs/)"
    echo -e "---------------------------------------------------------------\033[0m"

    source /opt/intel/apphsm/env_*/bin/activate && \
        python3 /opt/intel/apphsm/apphsm.py && \
        deactivate
