FROM {{ intel_media_analytics_image_src }}:{{ intel_media_analytics_image_tag }}

ARG http_proxy
ARG https_proxy

USER root
RUN apt-get update && apt-get install -y --no-install-recommends git

ENV  HOME=/home/{{ intel_media_analytics_pod_username }}
USER {{ intel_media_analytics_pod_username }}
WORKDIR /home/{{ intel_media_analytics_pod_username }}
COPY --chown={{ intel_media_analytics_pod_username }}:{{ intel_media_analytics_pod_username }} install-models.sh .
COPY --chown={{ intel_media_analytics_pod_username }}:{{ intel_media_analytics_pod_username }} media-analytics-test.sh .
RUN python3 -m pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir "openvino-dev==2022.3.0"
RUN  chmod +x install-models.sh && chmod +x media-analytics-test.sh && ./install-models.sh

HEALTHCHECK NONE
