##
##   Copyright (c) 2020-2023 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: copy Helm chart resource definition to controller node
  copy:
    src: "{{ (role_path, 'charts/gpu-aware-scheduling') | path_join }}"
    dest: "{{ (project_root_dir, 'charts') | path_join }}"
    mode: preserve

- name: populate gas Helm chart values template and push to controller node
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    mode: preserve
  loop:
    - {
      src: "gas-values.yaml.j2",
      dest: "{{ (project_root_dir, 'charts/gpu-aware-scheduling/values.yaml') | path_join }}"
    }
    - {
      src: "gas-chart.yaml.j2",
      dest: "{{ (project_root_dir, 'charts/gpu-aware-scheduling/Chart.yaml') | path_join }}"
    }

- name: install GAS helm chart
  command: >-
    helm upgrade -i {{ gas_name }}
    --namespace {{ pas_namespace }}
    ./
  args:
    chdir: "{{ (project_root_dir, 'charts/gpu-aware-scheduling') | path_join }}"
  retries: 5
  delay: 5
  register: result
  until: result.rc == 0
  changed_when: true
