##
##   Copyright (c) 2020-2021 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: verify that intel_pstate driver is enabled
  fail:
     msg: intel_pstate must be enabled for SST-BF to work on CLX platform
  when: intel_pstate is defined and intel_pstate == "disable"

- name: install Python 3 and Git from package repository
  package:
    name:
      - python3
      - git

- name: Clone CommsPowerManagement repository
  git:
    repo: "{{ clx_sst_bf_git_url }}"
    dest: "{{ clx_sst_bf_dir }}"
    force: yes
    version: a3a1869fd88eff5b2b872f447ca69b866e3d318e

- name: copy scripts to /usr/local/bin
  copy:
    src: "{{ clx_sst_bf_dir }}/sst_bf.py"
    dest: "{{ clx_sst_bf_exec }}"
    mode: u=rwx,g=rx,o=rx
    remote_src: yes

- name: ensure that MSR module is present
  modprobe:
    name: msr
    state: present

- name: setup MSR module loading on boot
  copy:
    src: msr.conf
    dest: /etc/modules-load.d/msr.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Validate sst mode
  assert:
    that: clx_sst_bf_mode in ['s', 'm', 'r']
    fail_msg: "The 'clx_sst_bf_mode' variable must be set to 's', 'm' or 'r'. Please update your host vars."

- name: install the sst-bf-configure systemd service
  template:
    src: sst-bf-configure.service.j2
    dest: /lib/systemd/system/sst-bf-configure.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: run sst-bf-configure service on boot
  systemd:
    daemon_reload: yes
    state: restarted
    name: sst-bf-configure
    enabled: yes
