##
##   Copyright (c) 2020-2023 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: check if the OpenSSl configuration dir exists
  stat:
    path: "{{ openssl_engine_dir }}"
  register: engine_stat_result
  when:
    - inventory_hostname in groups['kube_node']

- name: enable OpenSSL*Engine
  include_tasks: openssl_engine_config.yml
  when:
    - inventory_hostname in groups['kube_node']
    - engine_stat_result.stat.exists

- name: OpenSSL*Engine enablement skipped
  debug:
    msg: "OpenSSL*Engine enablement skipped, need to set openssl_install to true in host vars"
  when:
    - inventory_hostname in groups['kube_node']
    - not engine_stat_result.stat.exists
