##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: create CPU Control Plane directory
  ansible.builtin.file:
    path: "{{ cpu_ctlplane_local_build_dir }}"
    state: directory
    mode: 0755

- name: clone CPU Control Plane to the controller node
  ansible.builtin.git:
    repo: "{{ cpu_ctlplane_git_url }}"
    version: "{{ cpu_ctlplane_commit_hash }}"
    dest: "{{ cpu_ctlplane_local_build_dir }}"
    force: yes

# docker is used as container runtime:
- name: prepare containers images
  block:
    - name: compile local CPU Control Plane
      community.general.make:
        chdir: "{{ cpu_ctlplane_local_build_dir }}"

    - name: build local CPU Control Plane image
      ansible.builtin.command: >-
        docker build -f ./docker/Dockerfile -t {{ registry_local_address }}/{{ cpu_ctlplane_local_build_name }}:{{ cpu_ctlplane_local_tag_name }} ./
      args:
        chdir: "{{ (cpu_ctlplane_local_build_dir) | path_join }}"
      changed_when: true

    - name: push the local CPU Control Plane image to local registry
      ansible.builtin.command: >-
        docker push {{ registry_local_address }}/{{ cpu_ctlplane_local_build_name }}:{{ cpu_ctlplane_local_tag_name }}
      changed_when: true
  when:
    - container_runtime == "docker"

# containerd is used as container runtime:
- name: prepare containers images
  block:
    - name: compile local CPU Control Plane
      community.general.make:
        chdir: "{{ cpu_ctlplane_local_build_dir }}"

    - name: build local CPU Control Plane image
      ansible.builtin.command: >-
        podman build -f ./docker/Dockerfile -t {{ registry_local_address }}/{{ cpu_ctlplane_local_build_name }}:{{ cpu_ctlplane_local_tag_name }} ./
      args:
        chdir: "{{ (cpu_ctlplane_local_build_dir) | path_join }}"
      changed_when: true

    - name: push the local CPU Control Plane image to local registry
      ansible.builtin.command: >-
        podman push {{ registry_local_address }}/{{ cpu_ctlplane_local_build_name }}:{{ cpu_ctlplane_local_tag_name }}
      changed_when: true
  when:
    - container_runtime == "containerd"
