---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-kube-sriov-device-plugin-amd64
  namespace: {{ .Values.namespace }}
  labels:
    tier: node
    app: sriovdp
spec:
  template:
    metadata:
      labels:
        tier: node
        app: sriovdp
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: {{ .Release.Name }}-sriov-device-plugin
      containers:
      - name: kube-sriovdp
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - --log-dir=sriovdp
        - --log-level= {{ .Values.log.level }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/
          readOnly: false
        - name: log
          mountPath: /var/log
        - name: config-volume
          mountPath: /etc/pcidp
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/
        - name: log
          hostPath:
            path: /var/log
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-sriovdp-config
            items:
            - key: config.json
              path: config.json
