#!/bin/bash
#
# Copyright (c) 2020 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

QAT_SRIOV_NUMVFS_MAPPINGS=${QAT_SRIOV_NUMVFS_MAPPINGS:-"/etc/bmra/bmra_sriov_qat_numvfs"}

setup_vfs() {
    echo "Setting up VFs"
    if [[ ! -r "${QAT_SRIOV_NUMVFS_MAPPINGS}" ]]; then
        echo "File ${QAT_SRIOV_NUMVFS_MAPPINGS} doesn't exist, no VFs will be created"
        return 0
    fi

    while read -r pci_address numvfs; do
        if [[ ${pci_address} == "" ]] || [[ ${numvfs} == "" ]]; then
            echo "Empty PCI address or number of VFs, skipping..."
            continue
        fi

        numvfs_path="/sys/bus/pci/devices/${pci_address}/sriov_numvfs"
        if [[ ! -e "${numvfs_path}" ]]; then
            echo "Could not find sriov_numvfs for device ${pci_address}, skipping..."
            continue
        fi

        read -r current_vfs < "${numvfs_path}"

        echo "Setting up ${numvfs} Virtual Functions on ${pci_address}"
        if [[ ${current_vfs} -ne ${numvfs} ]]; then
            # if change is needed we must reset it first
            echo 0 > "${numvfs_path}"
            echo "${numvfs}" > "${numvfs_path}"
        fi

    done < "${QAT_SRIOV_NUMVFS_MAPPINGS}"
}

setup_vfs
