##
##   Copyright (c) 2020-2023 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: clone TCS repo
  git:
    repo: "{{ tcs_git_repo_url }}"
    dest: "{{ tcs_git_path }}"
    version: "{{ tcs_git_version }}"
    force: true

- name: update Makefile with proper tag
  replace:
    path: "{{ (tcs_git_path, 'Makefile') | path_join }}"
    regexp: '^IMG_TAG.*$'
    replace: 'IMG_TAG ?= {{ tcs_image_tag }}'
    mode: 0644

# this task should be removed when TCS fix issue with containerd
- name: replace chown with echo
  replace:
    path: "{{ (tcs_git_path, 'config', 'manager', 'tcs_issuer.yaml') | path_join }}"
    regexp: '.*"/bin/chown", "5000:5000".*'
    replace: '        command: ["/bin/echo"]'
  when:
    - container_runtime != "docker"

- name: create tcs namespace
  k8s:
    name: "{{ tcs.namespace }}"
    kind: Namespace
    state: present

- name: update TCS config - kustomization file
  lineinfile:
    path: "{{ (tcs_git_path, 'config', 'default', 'kustomization.yaml') | path_join }}"
    regexp: '^namespace:.*$'
    line: "namespace: {{ tcs.namespace }}"
    state: present
    mode: 0644

- name: update version in TCS chart value file
  lineinfile:
    path: "{{ (tcs_git_path, 'charts', 'values.yaml') | path_join }}"
    regexp: '^  tag:.*$'
    line: "  tag: {{ tcs_git_version }}"
    state: present
    mode: 0644

- name: find rolebinding manifests to fix subject namespaces
  find:
    paths: "{{ (tcs_git_path, 'config', 'rbac') | path_join }}"
    patterns: "*role_binding.yaml"
  register: rolebinding_manifests
  changed_when: false

- name: fix rolebindings subject namespaces due to kustomize bug.
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^(\s+)namespace:.*$'
    line: '\1namespace: {{ tcs.namespace }}'
    backrefs: yes
    state: present
    mode: 0644
  loop: "{{ rolebinding_manifests.files }}"

- name: execute go command to update tcs dependencies
  command: go mod tidy
  args:
    chdir: "{{ tcs_git_path }}"
  changed_when: true

- name: deploy TCS CRDs
  make:
    target:
      install
    chdir: "{{ tcs_git_path }}"

- name: deploy TCS
  make:
    target:
      deploy
    chdir: "{{ tcs_git_path }}"
  environment:
    REGISTRY: "{{ (tcs.build_image_locally) | ternary(registry_local_address, 'docker.io') }}"
    IMG_TAG: "{{ tcs_image_tag }}"
