{
 "title": "Intel XPU Manager Exporter",
 "tags": [ "xpum" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(xpum_power_watts, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xpum_engine_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xpum_engine_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "xpum_frequency_mhz{node=\"$Node\"}*1000000",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}: {{type}}"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xpum_frequency_mhz{node=\"$Node\"}*1000000",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}: {{type}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "xpum_temperature_celsius{node=\"$Node\", location=\"gpu\"}",
     "legendFormat": "avg: {{pci_bdf}}/{{sub_dev}}"
    },
    {
     "expr": "xpum_max_temperature_celsius{node=\"$Node\", location=\"gpu\"}",
     "legendFormat": "max: {{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xpum_temperature_celsius{node=\"$Node\", location=\"gpu\"}",
     "legendFormat": "avg: {{pci_bdf}}/{{sub_dev}}"
    },
    {
     "expr": "xpum_max_temperature_celsius{node=\"$Node\", location=\"gpu\"}",
     "legendFormat": "max: {{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "xpum_temperature_celsius{node=\"$Node\", location=\"mem\"}",
     "legendFormat": "avg: {{pci_bdf}}/{{sub_dev}}"
    },
    {
     "expr": "xpum_max_temperature_celsius{node=\"$Node\", location=\"mem\"}",
     "legendFormat": "max: {{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xpum_temperature_celsius{node=\"$Node\", location=\"mem\"}",
     "legendFormat": "avg: {{pci_bdf}}/{{sub_dev}}"
    },
    {
     "expr": "xpum_max_temperature_celsius{node=\"$Node\", location=\"mem\"}",
     "legendFormat": "max: {{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "xpum_power_watts{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xpum_power_watts{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "xpum_energy_joules_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xpum_energy_joules_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_memory_used_bytes{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Memory Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_memory_read_bytes_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Mem Read Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(xpum_memory_read_bytes_total{node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Memory Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_memory_write_bytes_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Mem Write Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(xpum_memory_write_bytes_total{node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xpum_memory_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xpum_memory_bandwidth_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Engine Group Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xpum_engine_group_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}: {{type}}"
    }
   ]
  },
  {
   "title": "EU Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xpum_eu_active_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "PCIe Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_pcie_read_bytes_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "PCIe Read Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(xpum_pcie_read_bytes_total{node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "PCIe Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_pcie_write_bytes_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "PCIe Write Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(xpum_pcie_write_bytes_total{node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "EU Idle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xpum_eu_idle_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Programming Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "xpum_programming_errors_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Cache Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "xpum_cache_errors_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}: {{type}}"
    }
   ]
  },
  {
   "title": "Driver Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "xpum_driver_errors_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}: {{type}}"
    }
   ]
  },
  {
   "title": "EU Stall",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xpum_eu_stall_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Reset Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "xpum_resets_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}"
    }
   ]
  },
  {
   "title": "Non Compute Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "targets": [
    {
     "expr": "xpum_non_compute_errors_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}: {{type}}"
    }
   ]
  },
  {
   "title": "Per Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xpum_per_engine_ratio{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}}: {{type}}-{{engine_id}}"
    }
   ]
  },
  {
   "title": "Fabric Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_fabric_tx_bytes_total{node=\"$Node\"}",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}} -> {{dst_pci_bdf}}/{{dst_sub_dev}}"
    }
   ]
  },
  {
   "title": "Fabric Transmit Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(xpum_fabric_tx_bytes_total{node=\"$Node\"}[10s])",
     "legendFormat": "{{pci_bdf}}/{{sub_dev}} -> {{dst_pci_bdf}}/{{dst_sub_dev}}"
    }
   ]
  }
 ]
}