# Copyright (c) 2016-2017, Intel Corporation.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

---
  - name: Install docker
    include: "{{ ansible_os_family }}.yml"

  - name: create docker service config dir
    file: path=/etc/systemd/system/docker.service.d state=directory

  - name: create docker mountflags config
    template: src=mountflags-conf.j2 dest=/etc/systemd/system/docker.service.d/mountflags.conf owner=root mode=0644
    notify:
     - start docker service 

  - name: cgroup systemd
    template: src=cgroup_systemd-conf.j2 dest=/etc/systemd/system/docker.service.d/cgroup_systemd.conf owner=root mode=0644
    notify:
     - start docker service 
    when: ansible_os_family == "RedHat"

  - name: create docker proxy config
    template: src=http-proxy-conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf owner=root mode=0644
    when: '"http_proxy" in calc_proxy_env or "https_proxy" in calc_proxy_env'
    notify:
     - start docker service 

  - name: start docker service
    systemd:
     name: docker
     state: restarted
     enabled: yes

  - meta: flush_handlers
