apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-sgx-aesmd-demo
  namespace: {{ .Release.Namespace }}
  labels:
    app: intel-sgx-aesmd-demo
spec:
  selector:
    matchLabels:
      app: intel-sgx-aesmd-demo
  template:
    metadata:
      labels:
        app: intel-sgx-aesmd-demo
      annotations:
        sgx.intel.com/quote-provider: "aesmd"
    spec:
      hostNetwork: true
      containers:
      - name: {{ .Release.Name }}-aesmd
        image: "{{ .Values.sgx_aesmd_image.repository }}:{{ .Values.sgx_aesmd_image.tag }}"
        securityContext:
          readOnlyRootFilesystem: true
        resources:
          limits:
            sgx.intel.com/epc: "1Mi"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: aesmdconf
          mountPath: /etc/aesmd.conf
          subPath: aesmd.conf
        - name: qplconf
          mountPath: /etc/sgx_default_qcnl.conf
          subPath: sgx_default_qcnl.conf
      volumes:
      - name: aesmdconf
        configMap:
          name: sgx-attestation-conf
          items:
          - key: aesmd.conf
            path: aesmd.conf
      - name: qplconf
        configMap:
          name: sgx-attestation-conf
          items:
          - key: sgx_default_qcnl.conf
            path: sgx_default_qcnl.conf