##
##   Copyright (c) 2020-2023 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
# This var is not intended to be customized by user
# Define respective field in the group_vars/all.yml instead
kmra_oran:
  apphsm:
    oran_netopeer2_cert_user_id: "ctk_loadkey_user_id_01234"
    enabled: true
    app_keys:
      - id: "unique_id_1234s_cu"
        token_name: "token_server_cu"
        pin: "1234"
        key_name: "server_cu.key"
        key_path: "/opt/intel/custom_tls/server_cu.key"
        token_cert: "/opt/intel/custom_tls/server_cu.crt"
        crt_subj:
          O: "SampleOrganisation"
          CN: "localhost"
      - id: "unique_id_1234s_du"
        token_name: "token_server_du"
        pin: "1234"
        key_name: "server_du.key"
        key_path: "/opt/intel/custom_tls/server_du.key"
        token_cert: "/opt/intel/custom_tls/server_du.crt"
        crt_subj:
          O: "SampleOrganisation"
          CN: "localhost"
      - id: "unique_id_1234s_ric"
        token_name: "token_server_ric"
        pin: "1234"
        key_name: "server_ric.key"
        key_path: "/opt/intel/custom_tls/server_ric.key"
        token_cert: "/opt/intel/custom_tls/server_ric.crt"
        crt_subj:
          O: "SampleOrganisation"
          CN: "localhost"
      - id: "unique_id_1234c"
        token_name: "token_client"
        pin: "1234"
        key_name: "client.key"
        key_path: "/opt/intel/custom_tls/client.key"
        token_cert: "/opt/intel/custom_tls/client.crt"
        crt_subj:
          O: "SampleOrganisation"
          CN: "localhost"
    ecdsa_keys: "true"
  oran:
    enabled: true
    local_build: true
    oran_image_staging_location: "/tmp/oran/oran.tar"
    oran_image_checksum: "3c17855ee876a2db3b8ea5b8dd0dfa0ac68b52b2a243c24704bee9678b0cf0c8"
    sw_provider_name: "oranprovider"
    sw_provider_crt_subj:
      O: "SampleOrganisation"
      CN: "localhost"
    sw_operator_name: "oranoperator"
    sw_operator_crt_subj:
      O: "SampleOrganisation"
      CN: "localhost"

  oran_netopeer2_server:
    enabled: true
    release_name: "kmra-oran-netopeer2-server"
    helm_values_file: "{{ (project_root_dir, 'charts', 'kmra-oran-netopeer2-server-values.yml') | path_join }}"
    chart_path: "{{ (project_root_dir, 'charts', 'kmra-oran-netopeer2-server') | path_join }}"
    image_repo: "{{ registry_local_address }}"
    image_name: "oran/ctk_loadkey"
    # image_tag: ""
    init_image_repo: "{{ registry_local_address }}"
    init_image_name: "oran/busybox"
    init_image_tag: "1.35"
    client_token: "token_server"
    client_key_label: "client_key_priv"
    test_unique_uid: "unique_id_1234s"
    default_user_pin: "1234"
    default_so_pin: "12345678"
    default_client_token_id: "0xDEADBEEF"
    use_secure_cert: false
    oran_image_repo: "{{ registry_local_address }}"
    oran_image_name: "oran/oran"
    # oran_image_tag: ""
    oran_netopeer2_server_hostname: "kmra-oran-netopeer2-server"
    oran_netopeer2_server_port: 6513
    pkcs11_proxy_tls_psk: "test:e9622c85018998993fcc16f5ce9c15e9"
    pkcs11_proxy_tls_psk_file: "/etc/p11_proxy_tls.psk"
    pkcs11_daemon_socket_hostname: "127.0.0.1"
    pkcs11_daemon_socket_port: 5657
    crt_subj:
      O: "oran"
      OU: "ctk_loadkey_user_id_01234"

  oran_netopeer2_client:
    enabled: true
    release_name: "kmra-oran-netopeer2-client"
    helm_values_file: "{{ (project_root_dir, 'charts', 'kmra-oran-netopeer2-client-values.yml') | path_join }}"
    chart_path: "{{ (project_root_dir, 'charts', 'kmra-oran-netopeer2-client') | path_join }}"
    image_repo: "{{ registry_local_address }}"
    image_name: "oran/ctk_loadkey"
    # image_tag: ""
    init_image_repo: "{{ registry_local_address }}"
    init_image_name: "oran/busybox"
    init_image_tag: "1.35"
    client_token: "token_client"
    client_key_label: "client_key_priv"
    test_unique_uid: "unique_id_1234c"
    default_user_pin: "1234"
    default_so_pin: "12345678"
    default_client_token_id: "0xDEADBEEF"
    use_secure_cert: false
    oran_image_repo: "{{ registry_local_address }}"
    oran_image_name: "oran/oran"
    # oran_image_tag: ""
    oran_netopeer2_server_hostname: "kmra-oran-netopeer2-server"
    oran_netopeer2_server_port: 6513
    pkcs11_proxy_tls_psk: "test:e9622c85018998993fcc16f5ce9c15e9"
    pkcs11_proxy_tls_psk_file: "/etc/p11_proxy_tls.psk"
    pkcs11_daemon_socket_hostname: "127.0.0.1"
    pkcs11_daemon_socket_port: 5657
    crt_subj:
      O: "oran"
      OU: "ctk_loadkey_user_id_01234"
