{
 "title": "CPU",
 "tags": [ "collectd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Average CPU freq",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_cpufreq{exported_instance=\"${instance}\"})\n/\ncount(count by (cpufreq) (collectd_cpufreq{exported_instance=\"${instance}\"}))",
     "legendFormat": "frequency"
    }
   ]
  },
  {
   "title": "CPU Frequencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "collectd_cpufreq{exported_instance=\"${instance}\"}",
     "legendFormat": "{{cpufreq}}"
    }
   ]
  },
  {
   "title": "CPU Total Idle",
   "type": "graph",
   "description": "CPU Idle",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_cpu_total{type=\"idle\", exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_cpu_total{type=\"user\", exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Interrupt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_cpu_total{type=\"interrupt\", exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_cpu_total{type=\"system\", exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Nice",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_cpu_total{type=\"nice\", exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Steal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_cpu_total{type=\"steal\", exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Wait",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_cpu_total{type=\"wait\", exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU SoftIRQ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_cpu_total{type=\"softirq\", exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "tags": [ "collectd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disk IO time 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_io_time_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk IO time 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_io_time_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk time 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_time_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk time 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_time_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk merged operations 0",
   "type": "graph",
   "description": "Disk merged 0 total",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Merged Operations/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_merged_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk merged operations 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Merged Operations/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_merged_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk octets 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_octets_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk octets 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_octets_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk operations 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Operations/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_ops_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk operations 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Operations/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_disk_disk_ops_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}
{
 "title": "Intel",
 "tags": [ "collectd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "LLC Occupancy",
   "type": "graph",
   "description": "Intel RDT LLC Bytes\nlast level cache occupancy (CMT)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "collectd_intel_rdt_bytes{type=\"llc\", exported_instance=\"${instance}\"}",
     "legendFormat": "{{ intel_rdt }}"
    }
   ]
  },
  {
   "title": "IPC",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ipc", "label": "Instructions per clock" }
   ],
   "targets": [
    {
     "expr": "collectd_intel_rdt_ipc{exported_instance=\"${instance}\"}",
     "legendFormat": "{{ intel_rdt }}"
    }
   ]
  },
  {
   "title": "MBL",
   "type": "graph",
   "description": "the bandwidth of accessing memory associated with the local socket (MBM)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_intel_rdt_memory_bandwidth_total{exported_instance=\"${instance}\", type=\"local\"}[$__interval])",
     "legendFormat": "{{intel_rdt}}"
    }
   ]
  },
  {
   "title": "MBR",
   "type": "graph",
   "description": "the bandwidth of accessing the remote socket (MBM)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_intel_rdt_memory_bandwidth_total{exported_instance=\"${instance}\", type=\"remote\"}[$__interval])",
     "legendFormat": "{{intel_rdt}}"
    }
   ]
  }
 ]
}
{
 "title": "IPMI",
 "tags": [ "collectd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "collectd_ipmi_power{exported_instance=\"${instance}\", ipmi=\"cpu power unspecified (0.1)\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Memory power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "collectd_ipmi_power{exported_instance=\"${instance}\", ipmi=\"memory power unspecified (0.1)\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Total power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "collectd_ipmi_power{exported_instance=\"${instance}\", ipmi=\"total power unspecified (0.1)\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Netlink",
 "tags": [ "collectd" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Octets 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_octets_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Octets 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_octets_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Packets 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_packets_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Packets 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "pps", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_packets_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Multicast 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps", "label": "Multicast packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_multicast_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Packets drops 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Packets drops/s" }
   ],
   "targets": [
    {
     "expr": "#collectd_netlink_if_dropped_0_total{exported_instance=\"${instance}\"}\nrate(collectd_netlink_if_dropped_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Collisions",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Collisions/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_collisions_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Errors 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_errors_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Packets drops 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Packets drops/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_dropped_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "RX nohandler errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_rx_nohandler_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "RX errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_rx_errors_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "TX errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_tx_errors_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  },
  {
   "title": "Errors 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_netlink_if_errors_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ netlink }}"
    }
   ]
  }
 ]
}
{
 "title": "OVS",
 "tags": [ "collectd" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OVS collisions",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Collisions/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_collisions_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS packets drops 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Packets drops/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_dropped_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS packets drops 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Packets drops/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_dropped_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS errors 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_errors_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS errors 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_errors_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS packets 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_packets_1_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS packets 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_packets_0_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS RX octets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_rx_octets_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS RX errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_rx_errors_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  },
  {
   "title": "OVS TX octets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_tx_octets_total{exported_instance=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ ovs_stats }}"
    }
   ]
  }
 ]
}
{
 "title": "PKG Power",
 "tags": [ "collectd" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "TDP Power 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "collectd_package_0_TDP_power_power{exported_instance=\"${instance}\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "TDP Power 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "collectd_package_1_TDP_power_power{exported_instance=\"${instance}\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Power 0",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "collectd_package_0_power_power{exported_instance=\"${instance}\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Power 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "collectd_package_1_power_power{exported_instance=\"${instance}\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  }
 ]
}
{
 "title": "NUMA",
 "tags": [ "collectd" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "NUMA interleave_hit",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_numa_vmpage_action_total{exported_instance=\"${instance}\", type=\"interleave_hit\"}[$__interval])",
     "legendFormat": "{{ numa }}"
    }
   ]
  },
  {
   "title": "NUMA local_node",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_numa_vmpage_action_total{exported_instance=\"${instance}\", type=\"local_node\"}[$__interval])",
     "legendFormat": "{{ numa }}"
    }
   ]
  },
  {
   "title": "NUMA numa_foreign",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_numa_vmpage_action_total{exported_instance=\"${instance}\", type=\"numa_foreign\"}[$__interval])",
     "legendFormat": "{{ numa }}"
    }
   ]
  },
  {
   "title": "NUMA numa_hit",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_numa_vmpage_action_total{exported_instance=\"${instance}\", type=\"numa_hit\"}[$__interval])",
     "legendFormat": "{{ numa }}"
    }
   ]
  },
  {
   "title": "NUMA numa_miss",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_numa_vmpage_action_total{exported_instance=\"${instance}\", type=\"numa_miss\"}[$__interval])",
     "legendFormat": "{{ numa }}"
    }
   ]
  },
  {
   "title": "NUMA other_node",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_numa_vmpage_action_total{exported_instance=\"${instance}\", type=\"other_node\"}[$__interval])",
     "legendFormat": "{{ numa }}"
    }
   ]
  }
 ]
}
{
 "title": "Hugepages",
 "tags": [ "collectd" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Hugepages free",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_hugepages_vmpage_number{exported_instance=\"${instance}\", type=\"free\"}",
     "legendFormat": "{{ hugepages }}"
    }
   ]
  },
  {
   "title": "Hugepages used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_hugepages_vmpage_number{exported_instance=\"${instance}\", type=\"used\"}",
     "legendFormat": "{{ hugepages }}"
    }
   ]
  }
 ]
}
{
 "title": "EthStats",
 "tags": [ "collectd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Eth rx_bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ethstat_derive_total{exported_instance=\"${instance}\", type=\"rx_bytes\"}[$__interval])",
     "legendFormat": "{{ ethstat }}"
    }
   ]
  },
  {
   "title": "Eth tx_bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ethstat_derive_total{exported_instance=\"${instance}\", type=\"tx_bytes\"}[$__interval])",
     "legendFormat": "{{ ethstat }}"
    }
   ]
  },
  {
   "title": "Eth rx_broadcast",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ethstat_derive_total{exported_instance=\"${instance}\", type=\"rx_broadcast\"}[$__interval])",
     "legendFormat": "{{ ethstat }}"
    }
   ]
  },
  {
   "title": "Eth tx_broadcast",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ethstat_derive_total{exported_instance=\"${instance}\", type=\"tx_broadcast\"}[$__interval])",
     "legendFormat": "{{ ethstat }}"
    }
   ]
  },
  {
   "title": "Eth rx_multicast",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ethstat_derive_total{exported_instance=\"${instance}\", type=\"rx_multicast\"}[$__interval])",
     "legendFormat": "{{ ethstat }}"
    }
   ]
  },
  {
   "title": "ETH tx_multicast",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ethstat_derive_total{exported_instance=\"${instance}\", type=\"tx_multicast\"}[$__interval])",
     "legendFormat": "{{ ethstat }}"
    }
   ]
  }
 ]
}