{
 "title": "CPU",
 "tags": [ "telegraf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Temperature of CPU Core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "powerstat_core_cpu_temperature_celsius{host=\"${instance}\"}",
     "legendFormat": "{{ core_id }}"
    }
   ]
  },
  {
   "title": "CPU Core Frequencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "powerstat_core_cpu_frequency_mhz{host=\"${instance}\"}",
     "legendFormat": "{{cpu_id}}"
    }
   ]
  },
  {
   "title": "CPU Time Idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_time_idle{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Time User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_time_user{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Time Nice",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_time_nice{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Time System",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_time_system{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Time Steal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_time_steal{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Time SoftIRQ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_time_softirq{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Time IRQ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_time_irq{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Time IO Wait",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Jiffies" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_time_iowait{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage Guest",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_guest{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage Idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_idle{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage Idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_iowait{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage IRQ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_irq{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage SoftIRQ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_softirq{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage Nice",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_nice{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage Steal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_steal{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage System",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_system{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_usage_user{cpu!=\"cpu-total\", host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ cpu }}"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "tags": [ "telegraf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disk IO time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_io_time{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk IO read time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_time{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk IO write time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_write_time{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk IO writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_writes{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk IO reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_reads{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk IO merged reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_merged_reads{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk IO merged writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_merged_writes{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(disk_total{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_used{host=\"${instance}\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_free{host=\"${instance}\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}
{
 "title": "Intel",
 "tags": [ "telegraf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "LLC Occupancy",
   "type": "graph",
   "description": "Intel RDT LLC Bytes\nlast level cache occupancy (CMT)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rdt_metric_value{name=\"LLC\", host=\"${instance}\"}",
     "legendFormat": "{{ cores }}"
    }
   ]
  },
  {
   "title": "IPC",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ipc", "label": "Instructions per clock" }
   ],
   "targets": [
    {
     "expr": "rdt_metric_value{name=\"IPC\", host=\"${instance}\"}",
     "legendFormat": "{{ cores }}"
    }
   ]
  },
  {
   "title": "MBL",
   "type": "graph",
   "description": "the bandwidth of accessing memory associated with the local socket (MBM)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rdt_metric_value{host=\"${instance}\", name=\"MBL\"}",
     "legendFormat": "{{ cores }}"
    }
   ]
  },
  {
   "title": "MBR",
   "type": "graph",
   "description": "the bandwidth of accessing the remote socket (MBM)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rdt_metric_value{host=\"${instance}\", name=\"MBR\"}",
     "legendFormat": "{{ cores }}"
    }
   ]
  }
 ]
}
{
 "title": "IPMI",
 "tags": [ "telegraf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Power Supply 1 Input power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor_value{host=\"${instance}\", name=\"ps1_input_power\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Power Supply 1 temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor_value{host=\"${instance}\", name=\"ps1_temperature\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Power Supply 1 Curr Out",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor_value{host=\"${instance}\", name=\"ps1_curr_out_%\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}
{
 "title": "Net",
 "tags": [ "telegraf" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of bytes received by the interface",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "net_bytes_recv{host=\"${instance}\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Number of bytes sent by the interface",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "net_bytes_sent{host=\"${instance}\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Packets sent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "net_packets_sent{host=\"${instance}\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Packets receive",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "net_packets_recv{host=\"${instance}\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Receive errors detected by the interface",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "net_err_in{host=\"${instance}\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Transmit errors detected by the interface",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "net_err_out{host=\"${instance}\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Received packets dropped by the interface",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "net_drop_in{host=\"${instance}\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Transmitted packets dropped by the interface",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "net_drop_out{host=\"${instance}\"}",
     "legendFormat": "{{ interface }}"
    }
   ]
  }
 ]
}
{
 "title": "PKG Power",
 "tags": [ "telegraf" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Maximum Thermal Design Power (TDP) available for processor package",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "powerstat_package_thermal_design_power_watts{host=\"${instance}\"}",
     "legendFormat": "{{ package_id }}"
    }
   ]
  },
  {
   "title": "Current power consumption of processor package",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "powerstat_package_current_power_consumption_watts{host=\"${instance}\"}",
     "legendFormat": "{{ package_id }}"
    }
   ]
  },
  {
   "title": "Current power consumption of processor package DRAM subsystem",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "powerstat_package_current_dram_power_consumption_watts{host=\"${instance}\"}",
     "legendFormat": "{{ package_id }}"
    }
   ]
  }
 ]
}
{
 "title": "NUMA",
 "tags": [ "telegraf" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "NUMA hit",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_hit{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA local",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_local{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA foreign",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_foreign{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA miss",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_miss{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA other",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_other{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA interleave",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_interleave{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA pages migrated",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_pages_migrated{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA hint faults",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_hint_faults{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA hint faults local",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_hint_faults_local{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA pte updates",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_pte_updates{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "NUMA huge pte updates",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_vmstat_numa_huge_pte_updates{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}
{
 "title": "Hugepages",
 "tags": [ "telegraf" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Hugepages free",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_huge_pages_free{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Hugepages total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_huge_pages_total{host=\"${instance}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}
{
 "title": "EthStats",
 "tags": [ "telegraf" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Eth rx_bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(ethtool_rx_bytes{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Eth tx_bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(ethtool_tx_bytes{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Eth rx_broadcast",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(ethtool_rx_broadcast{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Eth tx_broadcast",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(ethtool_rx_broadcast{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Eth rx_multicast",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(ethtool_rx_multicast{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Eth tx_multicast",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Packets/s" }
   ],
   "targets": [
    {
     "expr": "rate(ethtool_rx_multicast{host=\"${instance}\"}[$__interval])",
     "legendFormat": "{{ interface }}"
    }
   ]
  }
 ]
}